apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scheduler.fullname" . }}-config
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
data:
  {{- if .Values.config }}
  {{- toYaml .Values.config | nindent 2 }}
  {{- end }}
