# Default values for leadflowx-scheduler.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: harbor.example.com/leadflowx-scheduler
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: harbor-registry

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: scheduler.leadflowx.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: scheduler-tls
      hosts:
        - scheduler.leadflowx.example.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/apps
          operator: Exists

# Application-specific configuration
config:
  logLevel: "info"
  environment: "development"
  enableMetrics: true
  kafkaBootstrapServers: "kafka.messaging.svc.cluster.local:9092"
  kafkaTopic: "leadflowx-scheduler-events"

# External services dependencies
externalServices:
  postgres:
    host: "postgresql.databases.svc.cluster.local"
    port: 5432
    database: "leadflowx"
    username: "postgres"
    existingSecret: "postgresql-credentials"
    passwordKey: "postgres-password"

  redis:
    host: "redis-master.databases.svc.cluster.local"
    port: 6379
    existingSecret: "redis-credentials"
    passwordKey: "redis-password"

vault:
  enabled: true
  authPath: "kubernetes"
  role: "scheduler"
  secretPath: "leadflowx/scheduler"

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
